theme: jekyll-theme-minimal
title: Tom Hartvigsen
baseurl: /thartvigsen.github.io/
avatar: https://github.com/Thartvigsen/thartvigsen.github.io/blob/master/profile.png

footer-links:
  email: twhartvigsen@wpi.edu
  github: thartvigsen
  linkedin: https://www.linkedin.com/in/thartvigsen/
  rss: RSS # just type anything here for a working RSS icon
