theme: jekyll-theme-minimal
#theme: minima
title: Tom Hartvigsen
avatar: https://github.com/Thartvigsen/thartvigsen.github.io/blob/master/profile.png
description: Ph.D. Candidate at Worcester Polytechnic Institute.
logo: /images/profile.png

footer-links:
  email: twhartvigsen@wpi.edu
  github: thartvigsen
  linkedin: https://www.linkedin.com/in/thartvigsen/
  rss: RSS # just type anything here for a working RSS icon

gems:
    - jekyll-sitemap
