theme: jekyll-theme-minimal
#theme: minima
title: Tom Hartvigsen
avatar: https://github.com/Thartvigsen/thartvigsen.github.io/blob/master/profile.png
description: Optimizing for minimal expected negative feedback.
logo: /images/profile.png

author:
    github: "thartvigsen"
    googlescholar: "https://scholar.google.com/citations?user=rIjeeRsAAAAJ&hl=en"

footer-links:
  email: twhartvigsen@wpi.edu
  github: thartvigsen
  linkedin: https://www.linkedin.com/in/thartvigsen/
  rss: RSS # just type anything here for a working RSS icon

gems:
    - jekyll-sitemap

